version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      nuget-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
        update-types: [version-update:semver-major]
