<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)key.snk</AssemblyOriginatorKeyFile>
    <Authors>Brice Lambson</Authors>
    <Copyright>© 2025-$([System.DateTime]::Today.Year) Brice Lambson. All rights reserved.</Copyright>
    <Product>Bricelam.PowerFx.Linq</Product>
  </PropertyGroup>
</Project>
