<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.21" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
        <PackageVersion Include="Microsoft.PowerFx.Core" Version="1.4.0" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageVersion Include="xunit.v3" Version="3.2.0" />
        <PackageVersion Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>
    <ItemGroup>
        <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
        <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.8.118" />
    </ItemGroup>
</Project>
