<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>Use Power Fx inside LINQ</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>$(PackageTags);linq</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bricelam.PowerFx\Bricelam.PowerFx.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" Visible="false" />
  </ItemGroup>

</Project>
