<Project>
  <Import Project="..\Directory.Build.props" />
  <PropertyGroup>
    <AnalysisMode>Recommended</AnalysisMode>
    <DebugType>embedded</DebugType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
    <PackageProjectUrl>https://bricelam.net/Bricelam.PowerFx.Linq</PackageProjectUrl>
    <PackageTags>powerfx</PackageTags>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
</Project>
