name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/bricelam/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
      - name: Publish 1
        continue-on-error: true
        #if: ${{ github.event_name != 'pull_request' }}
        run: |
          dotnet nuget list source
          dotnet nuget push artifacts/package/release/*.nupkg
      - name: Publish 2
        continue-on-error: true
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/bricelam/index.json --name github --username bricelam --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          dotnet nuget push artifacts/package/release/*.nupkg --source github
      - name: Publish 3
        continue-on-error: true
        run: dotnet nuget push artifacts/package/release/*.nupkg --source https://nuget.pkg.github.com/bricelam/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
